:spring_version: current
:project_id: gs-graphql-server
:icons: font
:source-highlighter: prettify

== What You Will Build
`http://localhost:8080/graphiql`에서 GraphQL 요청을 수신하는 서비스를 구축할 것입니다.


[[scratch]]
== Starting with Spring Initializr

To manually initialize the project:

. Navigate to https://start.spring.io.
. Gradle 또는 Maven 및 사용할 언어를 선택합니다. 이 가이드에서는 Java를 선택한 것으로 가정합니다.
. Dependencies를 클릭하고 Spring for GraphQL과 Spring Web을 선택합니다.
. Generate를 클릭합니다.
. 선택한 옵션으로 구성된 GraphQL 애플리케이션의 ZIP 파일을 다운로드합니다.


[[initial]]
== GraphQL에 대한 간략한 소개

GraphQL은 서버에서 데이터를 검색하기 위한 쿼리 언어입니다.
이는 REST, SOAP 또는 gRPC와 대체될 수 있는 언어입니다.
이 튜토리얼에서는 온라인 상점의 백엔드에서 특정 책의 세부 정보를 쿼리하는 방법에 대해 알아보겠습니다.

다음은 책 세부 정보를 검색하기 위해 GraphQL 서버에 보낼 수 있는 예시 요청입니다:

[source,graphql]
----
query bookDetails {
  bookById(id: "book-1") {
    id
    name
    pageCount
    author {
      firstName
      lastName
    }
  }
}
----

* id가 "book-1"인 책에 대한 쿼리 실행
* 책에 대해 id, name, pageCount 및 author를 반환
* 작성자에 대해 firstName 및 lastName을 반환

The response is in JSON. For example:

[source,json]
----
{
  "bookById": {
    "id":"book-1",
    "name":"Effective Java",
    "pageCount":416,
    "author": {
      "firstName":"Joshua",
      "lastName":"Bloch"
    }
  }
}
----

GraphQL의 중요한 특징은 스키마 언어를 정의하고 정적으로 타입이 지정된다는 것입니다.
서버는 요청이 쿼리할 수 있는 객체 유형 및 해당 객체가 포함하는 필드를 정확히 알고 있습니다.
또한 클라이언트는 스키마 세부 정보를 요청하기 위해 서버를 내부 검사할 수 있습니다.

참고: 이 튜토리얼에서 스키마라는 용어는 "GraphQL 스키마"를 가리키며, "JSON 스키마" 또는 "데이터베이스 스키마"와 관련이 없습니다.

== Schema
이전에 준비한 Spring for GraphQL 애플리케이션에서 src/main/resources/graphql 디렉토리를 생성합니다.
이 폴더에 schema.graphqls라는 새 파일을 다음 내용으로 추가합니다:

[source,graphql]
----
include::src/main/resources/graphql/schema.graphqls[]
----


이 튜토리얼에서는 Java에서이 스키마를 가진 GraphQL 서버를 구현하는 방법에 중점을 둡니다.

우리는 GraphQL 서비스의 예로서 특정 책의 세부 정보를 가져오기 위한 주요 단계를 다루겠습니다.
이는 포괄적인 API가 아닌 간단한 책 세부 정보를 가져오기 위한 API입니다.

모든 GraphQL 스키마에는 최상위 Query 유형이 있으며, 해당 유형 아래의 필드는 응용 프로그램에서 노출되는 쿼리 작업입니다.
여기서 스키마는 bookById라는 하나의 쿼리를 정의합니다. 이 쿼리는 특정 책의 세부 정보를 반환합니다.

또한 id, name, pageCount 및 author 필드를 가진 Book 유형과 firstName 및 lastName 필드를 가진 Author 유형을 정의합니다.

참고: 위에서 사용한 도메인 특화 언어는 "GraphQL 스키마"를 설명하는 데 사용되는 스키마 정의 언어 또는 SDL 이라고합니다.
자세한 내용은 https://graphql.org/learn/schema/[GraphQL 문서]를 참조하십시오.

== Source of the data

GraphQL의 중요한 특징 중 하나는 데이터가 어디에서든지 가져올 수 있다는 것입니다.
데이터는 데이터베이스, 외부 서비스 또는 정적인 인메모리 리스트에서 가져올 수 있습니다.

튜토리얼을 간소화하기 위해 책과 작가 데이터는 각각의 클래스 내부의 정적 리스트에서 가져옵니다.

=== Create the Book and Author data sources

이제 메인 애플리케이션 패키지의 GraphQlServerApplication 바로 옆에 `Book` 및 `Author` 클래스를 만듭니다.
다음 코드를 해당 클래스에 사용합니다:

[source,java]
----
include::src/main/java/com/example/graphql/Book.java[]
----

[source,java]
----
include::src/main/java/com/example/graphql/Author.java[]
----

== Adding code to fetch data

Spring for GraphQL은 https://docs.spring.io/spring-graphql/docs/current/reference/html/#controllers[어노테이션 기반 프로그래밍 모델]을 제공합니다.
컨트롤러에 어노테이션을 추가하여 특정 GraphQL 필드의 데이터를 검색하는 방법을 선언할 수 있습니다.

다음을 BookController.java에 `Book` 과 `Author` 옆에 메인 애플리케이션 패키지에 추가합니다:

[source,java]
----
include::src/main/java/com/example/graphql/BookController.java[]
----

@QuerMapping로 주석이 달린 bookById라는 이름의 메서드를 정의함으로써 이 컨트롤러는 쿼리 유형 아래에 정의된 Book을 어떻게 가져올지 선언합니다.
쿼리 필드는 메서드 이름에서 결정되지만, 어노테이션 자체에서 선언할 수도 있습니다.

참고: Spring for GraphQL은 RuntimeWiring.Builder를 사용하여 각 컨트롤러 메서드를 GraphQL Java graphql.schema.DataFetcher로 등록합니다.
DataFetcher는 쿼리 또는 스키마 필드의 데이터를 검색하기 위한 로직을 제공합니다.
Spring Boot GraphQL 스타터는 이 등록을 자동화하는 자동 구성을 제공합니다.

GraphQL Java 엔진에서 DataFetchingEnvironment은 필드별 인수 값의 맵에 액세스할 수 있습니다.
@Argument 주석을 사용하여 인수를 대상 객체에 바인딩하고 컨트롤러 메서드에 주입할 수 있습니다.
기본적으로 메서드 매개변수 이름은 인수를 찾는 데 사용되지만, 어노테이션 자체에서 지정할 수도 있습니다.

bookById 메서드는 특정 Book을 가져오는 방법을 정의하지만 관련 Author를 가져오는 것은 처리하지 않습니다.
요청이 작성자 정보를 요구하면 GraphQL Java는 이 필드를 검색해야 합니다.

@SchemaMapping 어노테이션은 핸들러 메서드를 GraphQL 스키마의 필드와 매핑하고 해당 필드의 DataFetcher로 선언합니다.
필드 이름은 메서드 이름으로 기본 설정되며, 타입 이름은 메서드에 주입된 소스/상위 객체의 간단한 클래스 이름으로 기본 설정됩니다.
이 예제에서는 필드가 기본적으로 author로 설정되고 타입은 Book으로 기본 설정됩니다.

자세한 내용은 https://docs.spring.io/spring-graphql/docs/current/reference/html/#controllers[Spring for GraphQL 어노테이션 기반 컨트롤러 기능 문서]를 참조하십시오.

== Running our first query

=== Enable the GraphiQL Playground

GraphiQL은 쿼리 작성 및 실행 외에도 다양한 기능을 제공하는 유용한 시각적 인터페이스입니다.
`application.properties` 파일에 다음 구성을 추가하여 GraphiQL을 활성화합니다.

[source,properties]
----
spring.graphql.graphiql.enabled=true
----

=== Boot the application

Spring 애플리케이션을 시작합니다. http://localhost:8080/graphiql로 이동합니다.

=== Run the query

쿼리를 입력하고 창 상단의 실행 버튼을 클릭합니다.

[source,graphql]
----
query bookDetails {
  bookById(id: "book-1") {
    id
    name
    pageCount
    author {
      id
      firstName
      lastName
    }
  }
}
----

=== Testing
Spring for GraphQL은 spring-graphql-test 아티팩트에서 GraphQL 테스트를 위한 도우미를 제공합니다. 이는 Spring Initializr로 생성된 프로젝트의 일부로 이미 포함되어 있습니다.

GraphQL 서비스를 철저히 테스트하려면 다양한 범위의 테스트가 필요합니다. 이 튜토리얼에서는 단일 컨트롤러에 초점을 맞춘 @GraphQlTest 슬라이스 테스트를 작성할 것입니다.
완전한 엔드 투 엔드 통합 테스트 및 서버 측 테스트를 지원하기 위한 다른 도우미도 제공됩니다.
자세한 내용은 https://docs.spring.io/spring-graphql/docs/current/reference/html/#testing[Spring for GraphQL Testing 문서] 및 Spring Boot 문서의 https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.testing.spring-boot-applications.spring-graphql-tests[자동 구성된 Spring for GraphQL 테스트]를 참조하십시오.

BookControllerTests.java라는 테스트 파일에 다음을 추가하십시오. 이 파일을 src/test/java/com/example/graphqlserver/ 폴더에 저장하십시오.

[source,java]
----
include::src/test/java/com/example/graphql/BookControllerTests.java[]
----

이 테스트는 몇 분 전 GraphiQL playground에서 요청한 bookDetails 쿼리와 유사한 GraphQL 쿼리를 참조합니다.
$id를 매개변수화하여 재사용 가능하도록 합니다.
이 쿼리를 bookDetails.graphql 파일에 src/test/resources/graphql-test 위치에 추가하십시오.

[source,graphql]
----
include::src/test/resources/graphql-test/bookDetails.graphql[]
----

테스트를 실행하고 결과가 GraphiQL Playground에서 수동으로 요청한 GraphQL 쿼리와 동일한지 확인합니다.

@GraphQlTest 주석은 컨트롤러 슬라이스 테스트를 작성할 때 유용합니다. 컨트롤러에 초점을 맞춘 테스트입니다.
@GraphQlTest는 전송 또는 서버가 관련되지 않고 Spring for GraphQL 인프라를 자동으로 구성합니다.
자동 구성을 통해 보일러플레이트 코드를 건너뛰고 빠르게 테스트를 작성할 수 있습니다.
이는 초점이 맞춰진 슬라이스 테스트이므로 @Controller 및 RuntimeWiringConfigurer와 같은 일부 빈만 스캔됩니다.
스캔되는 빈 목록은 https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#appendix.test-auto-configuration[문서]를 참조하십시오.

GraphQlTester는 전송과 관련없이 GraphQL 요청을 테스트하기 위한 일반적인 작업 흐름을 선언하는 계약입니다.
테스트에서 documentName과 필요한 변수를 제공한 다음 요청을 execute합니다.
그런 다음 JSON 경로를 사용하여 응답의 일부를 선택하고 해당 위치의 JSON이 예상 결과와 일치하는지 확인합니다.

축하합니다! 이 튜토리얼에서는 GraphQL 서비스를 구축하고 첫 번째 쿼리를 실행하며 첫 번째 GraphQL 테스트를 작성했습니다!

== 추가 자료

=== Documentation

- https://www.graphql-java.com/
- https://github.com/dondonz
- https://github.com/bbakerman
- https://github.com/andimarek
